from app.repositories.base_repository import BaseRepository
from app.repositories.dispositivo import DispositivoRepository
from app.repositories.estado_dispositivo import EstadoRepository
from app.repositories.evento import EventoRepository
from app.repositories.medicion import MedicionRepository
from app.repositories.sensor import SensorRepository
from app.repositories.tipo_evento import TipoEventoRepository
from app.repositories.tipo_medicion import TipoMedicionRepository
from app.repositories.tipo_sensor import TipoSensorRepository
from app.repositories.ubicacion import UbicacionRepository
from app.repositories.umbral import UmbralRepository
from app.repositories.unidad_medida import UnidadRepository